subarch: loong
target: stage3
version_stamp: systemd-mergedusr-stage3
rel_type: mergedusr
profile: default/linux/loong/22.0/la64v100/lp64d/systemd/merged-usr
snapshot_treeish: current.xz
source_subpath: mergedusr/stage1-loong-systemd-mergedusr-stage2
compression_mode: pixz
portage_confdir: /var/tmp/releng/releases/portage/stages
portage_prefix: releng
