subarch: amd64
target: stage1
version_stamp: systemd-mergedusr-stage2
rel_type: mergedusr
profile: default/linux/amd64/17.1/no-multilib/systemd/merged-usr
snapshot_treeish: current.xz
source_subpath: fsdk/stage1-amd64-systemd-mergedusr
compression_mode: pixz
portage_confdir: /var/tmp/releng/releases/portage/stages
portage_prefix: releng
