subarch: rv64_lp64d
target: stage3
version_stamp: systemd-mergedusr-stage3
rel_type: mergedusr
profile: default/linux/riscv/20.0/rv64gc/lp64d/systemd/merged-usr
snapshot_treeish: current.xz
source_subpath: mergedusr/stage1-rv64_lp64d-systemd-mergedusr-stage2
compression_mode: pixz
portage_confdir: /var/tmp/releng/releases/portage/stages
portage_prefix: releng
